name: build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Export env vars
        run: buildscripts/include/ci.sh export >>$GITHUB_ENV

      - uses: actions/cache@v4
        with:
          path: gh-cache/
          key: "prefix-${{ hashFiles('buildscripts/**/*.sh', 'buildscripts/include/*.sh') }}"
          restore-keys: ""
          enableCrossOsArchive: true

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf \
            automake \
            build-essential \
            cmake \
            pkg-config \
            libtool \
            ninja-build \
            python3 \
            python3-pip \
            nasm \
            unzip \
            wget \
            gettext \
            gperf
          python3 -m pip install --upgrade pip
          python3 -m pip install meson jinja2 jsonschema

      - name: Download deps
        run: |
          mkdir -p "$CACHE_FOLDER"
          buildscripts/include/ci.sh install
        env:
          CACHE_MODE: "folder"
          CACHE_FOLDER: "${{ github.workspace }}/gh-cache"

      - name: Build the release artifacts (all architectures)
        run: |
          set -x
          unset ANDROID_SDK_ROOT
          cd buildscripts
          ./download.sh > /dev/null
          for arch in armv7l arm64 x86 x86_64; do
            ./buildall.sh --arch "$arch" mpv
            ./buildall.sh --arch "$arch" python
          done
          ./buildall.sh -n mpv-android

      - name: Stage AAR artifact
        run: |
          mkdir -p dist
          cp app/build/outputs/aar/app-release.aar dist/mpvlib.aar

      - uses: actions/upload-artifact@v4
        with:
          name: mpvlib
          path: dist/mpvlib.aar
          if-no-files-found: error
